var colorschemes = [
    [["ASCII_Default.txt"], ["ASCII Default"]],
    [["AngleWyrms_Colorset.txt"], ["AngleWyrm's Colorset"]],
    [["Another_Natural_Scheme.txt"], ["Another Natural Scheme"]],
    [["Colorblind.txt"], ["Colorblind"]],
    [["Colorblind_Red-Green.txt"], ["Colorblind (Red/Green)"]],
    [["Dawnbringer.txt"], ["Dawnbringer"]],
    [["Higher-Visibility.txt"], ["Higher-Visibility"]],
    [["Lees_Colour_Scheme.txt"], ["Lee's Colour Scheme"]],
    [["Lees_Colour_Scheme-V2.txt"], ["Lee's Colour Scheme V2"]],
    [["Nagidal.txt"], ["Nagidal"]],
    [["Natural.txt"], ["Natural"]],
    [["Pastel_Bleach.txt"], ["Pastel Bleach"]],
    [["Putnams_Fortbent_Color_Scheme.txt"], ["Putnam's Fortbent Color Scheme"]],
    [["Rave_Fungus.txt"], ["Rave Fungus"]],
    [["Red-Green Colorblindness.txt"], ["Red-Green Colorblindness"]],
    [["Shady_Paint.txt"], ["Shady Paint"]],
    [["Taffer_Pastel.txt"], ["Taffer Pastel"]],
    [["Tango_Scheme.txt"], ["Tango Scheme"]],
    [["True_Brown.txt"], ["True Brown"]],
    [["True_CGA_Scheme.txt"], ["True CGA Scheme"]],
    [["Vherid_Ash.txt"], ["Vherid: Ash"]],
    [["Vherid_Bone.txt"], ["Vherid: Bone"]],
    [["Vherid_Dark Sand.txt"], ["Vherid: Dark Sand"]],
    [["Vherid_Default_Plus.txt"], ["Vherid: Default+"]],
    [["Vherid_Dusk.txt"], ["Vherid: Dusk"]],
    [["Vherid_Fields.txt"], ["Vherid: Fields"]],
    [["Vherid_Jade.txt"], ["Vherid: Jade"]],
    [["Vherid_Matrix.txt"], ["Vherid: Matrix"]],
    [["Vherid_Mishka.txt"], ["Vherid: Mishka"]],
    [["Vherid_Natural.txt"], ["Vherid: Natural"]],
    [["Vherid_NES.txt"], ["Vherid: NES"]],
    [["Vherid_Pastel.txt"], ["Vherid: Pastel"]],
    [["Vherid_Sorrow.txt"], ["Vherid: Sorrow"]],
    [["Vherid_Summer.txt"], ["Vherid: Summer"]],
    [["Vherid_Vintage.txt"], ["Vherid: Vintage"]],
    [["Vherid_Warm.txt"], ["Vherid: Warm"]],
    [["Vherid_Fallen.txt"], ["Vherid: Fallen"]],
    [["Vherid_Heat.txt"], ["Vherid: Heat"]],
    [["Vherid_Lazer.txt"], ["Vherid: Lazer"]],
    [["Vherid_Mud.txt"], ["Vherid: Mud"]],
    [["Solarized.txt"], ["Solarized"]],
    [
        ["Pseudo_Naturalistic_Color_Scheme.txt"],
        ["Pseudo Naturalistic Color Scheme"]
    ],
    [["Monokai.txt"], ["Monokai"]],
    [["elementary.txt"], ["elementary"]],
    [["CowThings_Color_Scheme.txt"], ["CowThing's Color Scheme"]],
    [["CowThings_Color_Scheme_Dark.txt"], ["CowThing's Color Scheme - Dark"]],
    [["(Yet)_Another_scheme.txt"], ["(Yet) Another scheme"]],
    [["Phoebus.txt"], ["Phoebus"]],
    [["Mayday.txt"], ["Mayday"]],
    [["Ironhand.txt"], ["Ironhand"]],
    [["Spacefox.txt"], ["Spacefox"]],
    [["GemSet.txt"], ["Gemset"]],
    [["CLA.txt"], ["CLA"]],
    [["Obsidian.txt"], ["Obsidian"]],
    [["Windows_10.txt"], ["Windows 10"]]
]
