var creatures = {
    "Dwarf Professions": [
        ["&#x00a9;", "Metalsmiths", "DGRAY"],
        ["&#x00a9;", "Fishery Worker", "BLUE"],
        ["&#x00a9;", "Craftsdwarfs", "LBLUE"],
        ["&#x00a9;", "Rangers", "GREEN"],
        ["&#x00a9;", "Jewelers", "LGREEN"],
        ["&#x00a9;", "Peasants", "CYAN"],
        ["&#x00a9;", "<i>On Break</i>", "LCYAN"],
        ["&#x00a9;", "Children", "RED"],
        ["&#x00a9;", "Engineers", "LRED"],
        ["&#x00a9;", "Administrators", "MAGENTA"],
        ["&#x00a9;", "Farmers", "BROWN"],
        ["&#x00a9;", "Woodworkers", "YELLOW"],
        ["&#x00a9;", "Miners", "LGRAY"],
        ["&#x00a9;", "Stoneworkers", "WHITE"]
    ],
    "Main Races": [
        ["&#x263a;", "Dwarf", "CYAN"],
        ["e", "Elf", "CYAN"],
        ["g", "Goblin", "LGRAY"],
        ["U", "Human", "CYAN"],
        ["k", "Kobold", "BROWN"]
    ],
    "Animal People": [
        ["a", "Antman", "DGRAY"],
        ["b", "Bat man", "DGRAY"],
        ["f", "Cave fish man", "WHITE"],
        ["s", "Cave swallow man", "DGRAY"],
        ["o", "Olm man", "WHITE"],
        ["r", "Reptile man", "GREEN"],
        ["r", "Rodent man", "DGRAY"],
        ["s", "Serpent man", "WHITE"]
    ],
    "Domestic Animals": [
        ["p", "Blue peafowl", "LBLUE"],
        ["c", "Cat", "DGRAY"],
        ["c", "Cavy", "LGRAY"],
        ["c", "Chicken", "BROWN"],
        ["C", "Cow", "BROWN"],
        ["d", "Dog", "BROWN"],
        ["d", "Duck", "GREEN"],
        ["D", "Donkey", "BROWN"],
        ["g", "Goat", "BROWN"],
        ["g", "Goose", "WHITE"],
        ["g", "Guineafowl", "DGRAY"],
        ["H", "Horse", "LGRAY"],
        ["L", "Llama", "WHITE"],
        ["M", "Mule", "BROWN"],
        ["C", "One-humped camel", "BROWN"],
        ["p", "Pig", "LMAGENTA"],
        ["r", "Rabbit", "BROWN"],
        ["R", "Reindeer", "BROWN"],
        ["s", "Sheep", "WHITE"],
        ["t", "Turkey", "LRED"],
        ["C", "Two-humped camel", "BROWN"],
        ["W", "Wagon", "BROWN"],
        ["W", "Water buffalo", "DGRAY"],
        ["Y", "Yak", "BROWN"]
    ],
    Megabeasts: [
        ["D", "Dragon", "GREEN"],
        ["H", "Hydra", "LRED"],
        ["R", "Roc", "WHITE"]
    ],
    "Semi-Megabeasts": [["E", "Ettin", "YELLOW"], ["G", "Giant", "CYAN"]],
    Nonexistent: [
        ["C", "Centaur", "BROWN"],
        ["C", "Chimera", "LGREEN"],
        ["G", "Griffon", "WHITE"]
    ],
    "Above Ground": [
        ["a", "Aardvark man", "LGRAY"],
        ["a", "Adder", "BROWN"],
        ["a", "Adder man", "BROWN"],
        ["A", "Alligator", "GREEN"],
        ["A", "Anaconda", "LGREEN"],
        ["A", "Anaconda man", "LGREEN"],
        ["a", "Anole man", "LGREEN"],
        ["a", "Armadillo", "LGRAY"],
        ["a", "Armadillo man", "LGRAY"],
        ["a", "Aye-aye", "LGRAY"],
        ["a", "Aye-aye man", "LGRAY"],
        ["b", "Badger", "LGRAY"],
        ["b", "Badger man", "LGRAY"],
        ["s", "Bark scorpion man", "YELLOW"],
        ["b", "Barn owl", "BROWN"],
        ["b", "Barn owl man", "BROWN"],
        ["B", "Beak dog", "RED"],
        ["b", "Beetle man", "RED"],
        ["g", "Bilou", "DGRAY"],
        ["B", "Black bear", "DGRAY"],
        ["B", "Black bear man", "DGRAY"],
        ["s", "Black mamba", "DGRAY"],
        ["s", "Black mamba man", "DGRAY"],
        ["g", "Black-crested gibbon", "DGRAY"],
        ["g", "Black-handed gibbon", "DGRAY"],
        ["M", "Blizzard man", "LCYAN"],
        ["p", "Blue peafowl", "LBLUE"],
        ["b", "Bluejay man", "LBLUE"],
        ["b", "Bobcat", "BROWN"],
        ["b", "Bobcat man", "BROWN"],
        ["b", "Bonobo", "DGRAY"],
        ["s", "Brown recluse spider man", "BROWN"],
        ["s", "Bushmaster", "BROWN"],
        ["s", "Bushmaster man", "BROWN"],
        ["b", "Bushtit man", "BROWN"],
        ["b", "Buzzard", "DGRAY"],
        ["b", "Buzzard man", "DGRAY"],
        ["c", "Capuchin", "WHITE"],
        ["c", "Capuchin man", "WHITE"],
        ["c", "Capybara", "BROWN"],
        ["c", "Capybara man", "BROWN"],
        ["c", "Cardinal man", "LRED"],
        ["c", "Cassowary", "DGRAY"],
        ["c", "Cassowary man", "DGRAY"],
        ["c", "Cavy", "LGRAY"],
        ["c", "Chameleon man", "LGREEN"],
        ["c", "Cheetah", "YELLOW"],
        ["c", "Cheetah man", "YELLOW"],
        ["c", "Chimpanzee", "DGRAY"],
        ["c", "Chinchilla", "LGRAY"],
        ["c", "Chinchilla man", "LGRAY"],
        ["c", "Chipmunk man", "BROWN"],
        ["c", "Coati", "BROWN"],
        ["c", "Coati man", "BROWN"],
        ["c", "Cockatiel man", "WHITE"],
        ["s", "Copperhead snake", "BROWN"],
        ["s", "Copperhead snake man", "BROWN"],
        ["c", "Cougar", "YELLOW"],
        ["c", "Cougar man", "BROWN"],
        ["C", "Cow", "BROWN"],
        ["c", "Coyote", "LGRAY"],
        ["c", "Coyote man", "LGRAY"],
        ["c", "Crow man", "DGRAY"],
        ["g", "Dark gnome", "CYAN"],
        ["D", "Deer", "BROWN"],
        ["d", "Deer man", "BROWN"],
        ["t", "Desert tortoise", "BROWN"],
        ["t", "Desert tortoise man", "BROWN"],
        ["d", "Dingo", "YELLOW"],
        ["d", "Dingo man", "YELLOW"],
        ["d", "Duck", "GREEN"],
        ["e", "Eagle", "BROWN"],
        ["e", "Eagle man", "BROWN"],
        ["e", "Echidna", "BROWN"],
        ["e", "Echidna man", "BROWN"],
        ["E", "Elephant", "LGRAY"],
        ["E", "Elephant man", "LGRAY"],
        ["E", "Elk", "BROWN"],
        ["E", "Elk man", "BROWN"],
        ["E", "Emu", "BROWN"],
        ["E", "Emu man", "BROWN"],
        ["f", "Firefly man", "LGREEN"],
        ["f", "Fly man", "DGRAY"],
        ["s", "Flying squirrel man", "BROWN"],
        ["b", "Foul blendec", "DGRAY"],
        ["f", "Fox", "RED"],
        ["f", "Fox man", "RED"],
        ["g", "Gazelle", "BROWN"],
        ["g", "Gazelle man", "BROWN"],
        ["A", "Giant aardvark", "LGRAY"],
        ["A", "Giant adder", "BROWN"],
        ["A", "Giant anaconda", "LGREEN"],
        ["A", "Giant anole", "LGREEN"],
        ["A", "Giant armadillo", "LGRAY"],
        ["A", "Giant aye-aye", "LGRAY"],
        ["B", "Giant badger", "LGRAY"],
        ["S", "Giant bark scorpion", "YELLOW"],
        ["B", "Giant barn owl", "BROWN"],
        ["B", "Giant beetle", "RED"],
        ["B", "Giant black bear", "DGRAY"],
        ["S", "Giant black mamba", "DGRAY"],
        ["B", "Giant bluejay", "LBLUE"],
        ["B", "Giant bobcat", "BROWN"],
        ["S", "Giant brown recluse spider", "BROWN"],
        ["S", "Giant bushmaster", "BROWN"],
        ["B", "Giant bushtit", "BROWN"],
        ["B", "Giant buzzard", "DGRAY"],
        ["C", "Giant capuchin", "WHITE"],
        ["C", "Giant capybara", "BROWN"],
        ["C", "Giant cardinal", "LRED"],
        ["C", "Giant cassowary", "DGRAY"],
        ["C", "Giant chameleon", "LGREEN"],
        ["C", "Giant cheetah", "YELLOW"],
        ["C", "Giant chinchilla", "LGRAY"],
        ["C", "Giant chipmunk", "BROWN"],
        ["C", "Giant coati", "BROWN"],
        ["C", "Giant cockatiel", "WHITE"],
        ["S", "Giant copperhead snake", "BROWN"],
        ["C", "Giant cougar", "BROWN"],
        ["C", "Giant coyote", "LGRAY"],
        ["C", "Giant crow", "DGRAY"],
        ["D", "Giant deer", "BROWN"],
        ["S", "Giant desert scorpion", "BROWN"],
        ["T", "Giant desert tortoise", "BROWN"],
        ["D", "Giant dingo", "YELLOW"],
        ["E", "Giant eagle", "BROWN"],
        ["E", "Giant echidna", "BROWN"],
        ["E", "Giant elephant", "LGRAY"],
        ["E", "Giant elk", "BROWN"],
        ["E", "Giant emu", "BROWN"],
        ["F", "Giant firefly", "LGREEN"],
        ["F", "Giant fly", "DGRAY"],
        ["S", "Giant flying squirrel", "BROWN"],
        ["F", "Giant fox", "RED"],
        ["G", "Giant gazelle", "BROWN"],
        ["G", "Giant gila monster", "LRED"],
        ["G", "Giant giraffe", "BROWN"],
        ["G", "Giant grackle", "DGRAY"],
        ["G", "Giant grasshopper", "LGREEN"],
        ["L", "Giant gray langur", "LGRAY"],
        ["S", "Giant gray squirrel", "LGRAY"],
        ["O", "Giant great horned owl", "LGRAY"],
        ["F", "Giant green tree frog", "LGREEN"],
        ["P", "Giant grey parrot", "LGRAY"],
        ["B", "Giant grizzly bear", "BROWN"],
        ["G", "Giant groundhog", "BROWN"],
        ["H", "Giant hamster", "LGRAY"],
        ["H", "Giant hare", "BROWN"],
        ["H", "Giant hedgehog", "BROWN"],
        ["H", "Giant hippo", "LGRAY"],
        ["M", "Giant hoary marmot", "LGRAY"],
        ["B", "Giant honey badger", "WHITE"],
        ["H", "Giant hornbill", "DGRAY"],
        ["H", "Giant hyena", "BROWN"],
        ["I", "Giant ibex", "BROWN"],
        ["I", "Giant iguana", "LGREEN"],
        ["I", "Giant impala", "BROWN"],
        ["J", "Giant jackal", "BROWN"],
        ["J", "Giant jaguar", "YELLOW"],
        ["J", "Giant jumping spider", "DGRAY"],
        ["K", "Giant kakapo", "GREEN"],
        ["K", "Giant kangaroo", "BROWN"],
        ["K", "Giant kea", "GREEN"],
        ["K", "Giant kestrel", "RED"],
        ["K", "Giant king cobra", "DGRAY"],
        ["K", "Giant kingsnake", "WHITE"],
        ["K", "Giant kiwi", "BROWN"],
        ["K", "Giant koala", "LGRAY"],
        ["L", "Giant leopard", "YELLOW"],
        ["G", "Giant leopard gecko", "YELLOW"],
        ["L", "Giant lion", "YELLOW"],
        ["L", "Giant lion tamarin", "YELLOW"],
        ["L", "Giant lizard", "BROWN"],
        ["L", "Giant lorikeet", "LRED"],
        ["L", "Giant louse", "BROWN"],
        ["L", "Giant lynx", "BROWN"],
        ["M", "Giant magpie", "DGRAY"],
        ["M", "Giant mandrill", "LBLUE"],
        ["M", "Giant mantis", "LGREEN"],
        ["L", "Giant masked lovebird", "LGREEN"],
        ["B", "Giant monarch butterfly", "LRED"],
        ["M", "Giant mongoose", "LGRAY"],
        ["M", "Giant monitor lizard", "BROWN"],
        ["M", "Giant moose", "BROWN"],
        ["M", "Giant mosquito", "DGRAY"],
        ["M", "Giant moth", "BROWN"],
        ["G", "Giant mountain goat", "WHITE"],
        ["M", "Giant muskox", "BROWN"],
        ["O", "Giant ocelot", "YELLOW"],
        ["C", "Giant one-humped camel", "BROWN"],
        ["O", "Giant opossum", "LGRAY"],
        ["O", "Giant oriole", "YELLOW"],
        ["O", "Giant osprey", "WHITE"],
        ["O", "Giant ostrich", "DGRAY"],
        ["P", "Giant pangolin", "BROWN"],
        ["P", "Giant parakeet", "LGREEN"],
        ["L", "Giant peach-faced lovebird", "LGREEN"],
        ["P", "Giant peregrine falcon", "BROWN"],
        ["B", "Giant polar bear", "WHITE"],
        ["P", "Giant porcupine", "BROWN"],
        ["S", "Giant python", "BROWN"],
        ["R", "Giant raccoon", "LGRAY"],
        ["S", "Giant rattlesnake", "LGRAY"],
        ["R", "Giant raven", "DGRAY"],
        ["P", "Giant red panda", "RED"],
        ["S", "Giant red squirrel", "BROWN"],
        ["M", "Giant rhesus macaque", "LGRAY"],
        ["R", "Giant rhinoceros", "LGRAY"],
        ["R", "Giant roach", "BROWN"],
        ["S", "Giant skink", "LGRAY"],
        ["S", "Giant skunk", "DGRAY"],
        ["S", "Giant sloth", "LGRAY"],
        ["B", "Giant sloth bear", "DGRAY"],
        ["S", "Giant slug", "BROWN"],
        ["S", "Giant snail", "LGRAY"],
        ["O", "Giant snowy owl", "WHITE"],
        ["S", "Giant sparrow", "BROWN"],
        ["M", "Giant spider monkey", "DGRAY"],
        ["S", "Giant stoat", "BROWN"],
        ["S", "Giant swan", "WHITE"],
        ["T", "Giant tapir", "WHITE"],
        ["T", "Giant thrips", "BROWN"],
        ["T", "Giant tick", "BROWN"],
        ["T", "Giant tiger", "YELLOW"],
        ["T", "Giant tortoise", "BROWN"],
        ["T", "Giant tortoise man", "BROWN"],
        ["C", "Giant two-humped camel", "BROWN"],
        ["V", "Giant vulture", "RED"],
        ["W", "Giant warthog", "BROWN"],
        ["W", "Giant weasel", "BROWN"],
        ["S", "Giant white stork", "WHITE"],
        ["B", "Giant wild boar", "BROWN"],
        ["W", "Giant wolf", "LGRAY"],
        ["W", "Giant wolverine", "BROWN"],
        ["W", "Giant wombat", "BROWN"],
        ["W", "Giant wren", "BROWN"],
        ["P", "Gigantic panda", "WHITE"],
        ["T", "Gigantic tortoise", "BROWN"],
        ["g", "Gila monster", "LRED"],
        ["g", "Gila monster man", "LRED"],
        ["G", "Giraffe", "BROWN"],
        ["G", "Giraffe man", "BROWN"],
        ["g", "Goose", "WHITE"],
        ["G", "Gorilla", "DGRAY"],
        ["g", "Grackle man", "DGRAY"],
        ["g", "Grasshopper man", "LGREEN"],
        ["g", "Gray gibbon", "DGRAY"],
        ["l", "Gray langur", "LGRAY"],
        ["l", "Gray langur man", "LGRAY"],
        ["s", "Gray squirrel man", "LGRAY"],
        ["g", "Guineafowl", "DGRAY"],
        ["o", "Great horned owl", "LGRAY"],
        ["o", "Great horned owl man", "LGRAY"],
        ["f", "Green tree frog man", "LGREEN"],
        ["p", "Grey parrot", "LGRAY"],
        ["p", "Grey parrot man", "LGRAY"],
        ["g", "Grimeling", "GREEN"],
        ["B", "Grizzly bear", "BROWN"],
        ["B", "Grizzly bear man", "BROWN"],
        ["g", "Groundhog", "BROWN"],
        ["g", "Groundhog man", "BROWN"],
        ["g", "Guineafowl", "DGRAY"],
        ["h", "Hamster man", "LGRAY"],
        ["h", "Hare", "BROWN"],
        ["h", "Hare man", "BROWN"],
        ["h", "Harpy", "BROWN"],
        ["h", "Hedgehog man", "BROWN"],
        ["m", "Hoary marmot", "LGRAY"],
        ["m", "Hoary marmot man", "LGRAY"],
        ["b", "Honey badger", "WHITE"],
        ["b", "Honey badger man", "WHITE"],
        ["h", "Hornbill", "DGRAY"],
        ["h", "Hornbill man", "DGRAY"],
        ["H", "Horse", "LGRAY"],
        ["h", "Hyena", "BROWN"],
        ["h", "Hyena man", "BROWN"],
        ["i", "Ibex", "BROWN"],
        ["i", "Ibex man", "BROWN"],
        ["w", "Ice wolf", "WHITE"],
        ["i", "Iguana", "LGREEN"],
        ["i", "Iguana man", "LGREEN"],
        ["i", "Impala", "BROWN"],
        ["i", "Impala man", "BROWN"],
        ["j", "Jackal", "BROWN"],
        ["j", "Jackal man", "BROWN"],
        ["J", "Jaguar", "YELLOW"],
        ["J", "Jaguar man", "YELLOW"],
        ["j", "Jumping spider man", "DGRAY"],
        ["k", "Kakapo", "GREEN"],
        ["k", "Kakapo man", "GREEN"],
        ["K", "Kangaroo", "BROWN"],
        ["K", "Kangaroo man", "BROWN"],
        ["k", "Kea", "GREEN"],
        ["k", "Kea man", "GREEN"],
        ["k", "Kestrel", "RED"],
        ["k", "Kestrel man", "RED"],
        ["k", "King cobra", "DGRAY"],
        ["k", "King cobra man", "DGRAY"],
        ["k", "Kingsnake", "WHITE"],
        ["k", "Kingsnake man", "WHITE"],
        ["k", "Kiwi", "BROWN"],
        ["k", "Kiwi man", "BROWN"],
        ["k", "Koala", "LGRAY"],
        ["k", "Koala man", "LGRAY"],
        ["l", "Leopard", "YELLOW"],
        ["l", "Leopard man", "YELLOW"],
        ["g", "Leopard gecko man", "YELLOW"],
        ["L", "Lion", "YELLOW"],
        ["L", "Lion man", "YELLOW"],
        ["l", "Lion tamarin man", "YELLOW"],
        ["l", "Lizard man", "BROWN"],
        ["L", "Llama", "WHITE"],
        ["l", "Lorikeet man", "LRED"],
        ["l", "Louse man", "BROWN"],
        ["l", "Lynx", "BROWN"],
        ["l", "Lynx man", "BROWN"],
        ["m", "Magpie man", "DGRAY"],
        ["m", "Mandrill", "LBLUE"],
        ["m", "Mandrill man", "LBLUE"],
        ["m", "Mantis man", "LGREEN"],
        ["l", "Masked lovebird man", "LGREEN"],
        ["b", "Monarch butterfly man", "LRED"],
        ["m", "Mongoose", "LGRAY"],
        ["m", "Mongoose man", "LGRAY"],
        ["M", "Monitor lizard", "BROWN"],
        ["M", "Monitor lizard man", "BROWN"],
        ["M", "Moose", "BROWN"],
        ["M", "Moose man", "BROWN"],
        ["m", "Mosquito man", "DGRAY"],
        ["m", "Moth man", "BROWN"],
        ["g", "Mountain gnome", "DGRAY"],
        ["g", "Mountain goat", "WHITE"],
        ["g", "Mountain goat man", "WHITE"],
        ["M", "Muskox", "BROWN"],
        ["M", "Muskox man", "BROWN"],
        ["N", "Nightwing", "DGRAY"],
        ["o", "Ocelot", "YELLOW"],
        ["o", "Ocelot man", "YELLOW"],
        ["O", "Ogre", "LGRAY"],
        ["C", "One-humped camel", "BROWN"],
        ["C", "One-humped camel man", "BROWN"],
        ["o", "Opossum", "LGRAY"],
        ["o", "Opossum man", "LGRAY"],
        ["O", "Orangutan", "BROWN"],
        ["o", "Oriole man", "YELLOW"],
        ["o", "Osprey", "WHITE"],
        ["o", "Osprey man", "WHITE"],
        ["O", "Ostrich", "DGRAY"],
        ["O", "Ostrich man", "DGRAY"],
        ["P", "Panda", "WHITE"],
        ["P", "Panda man", "WHITE"],
        ["p", "Pangolin", "BROWN"],
        ["p", "Pangolin man", "BROWN"],
        ["p", "Parakeet man", "LGREEN"],
        ["l", "Peach-faced lovebird man", "LGREEN"],
        ["p", "Peregrine falcon", "BROWN"],
        ["p", "Peregrine falcon man", "BROWN"],
        ["p", "Pig", "LMAGENTA"],
        ["g", "Pileated gibbon", "DGRAY"],
        ["B", "Polar bear", "WHITE"],
        ["B", "Polar bear man", "WHITE"],
        ["p", "Porcupine", "BROWN"],
        ["p", "Porcupine man", "BROWN"],
        ["S", "Python", "BROWN"],
        ["S", "Python man", "BROWN"],
        ["r", "Rabbit", "BROWN"],
        ["r", "Raccoon", "LGRAY"],
        ["r", "Raccoon man", "LGRAY"],
        ["r", "Rat man", "DGRAY"],
        ["s", "Rattlesnake", "LGRAY"],
        ["s", "Rattlesnake man", "LGRAY"],
        ["r", "Raven", "DGRAY"],
        ["r", "Raven man", "DGRAY"],
        ["p", "Red panda", "RED"],
        ["p", "Red panda man", "RED"],
        ["s", "Red squirrel man", "BROWN"],
        ["R", "Reindeer", "BROWN"],
        ["m", "Rhesus macaque", "LGRAY"],
        ["m", "Rhesus macaque man", "LGRAY"],
        ["R", "Rhinoceros", "LGRAY"],
        ["R", "Rhinoceros man", "LGRAY"],
        ["r", "Roach man", "BROWN"],
        ["C", "Saltwater crocodile", "GREEN"],
        ["C", "Saltwater crocodile man", "GREEN"],
        ["S", "Sasquatch", "BROWN"],
        ["s", "Satyr", "BROWN"],
        ["s", "Sheep", "WHITE"],
        ["s", "Siamang", "DGRAY"],
        ["g", "Silvery gibbon", "DGRAY"],
        ["s", "Skink man", "LGRAY"],
        ["s", "Skunk", "DGRAY"],
        ["s", "Skunk man", "DGRAY"],
        ["s", "Sloth", "LGRAY"],
        ["B", "Sloth bear", "DGRAY"],
        ["B", "Sloth bear man", "DGRAY"],
        ["s", "Sloth man", "LGRAY"],
        ["s", "Slug man", "BROWN"],
        ["s", "Snail man", "LGRAY"],
        ["o", "Snowy owl", "WHITE"],
        ["o", "Snowy owl man", "WHITE"],
        ["s", "Sparrow man", "BROWN"],
        ["m", "Spider monkey", "DGRAY"],
        ["m", "Spider monkey man", "DGRAY"],
        ["s", "Stoat", "BROWN"],
        ["s", "Stoat man", "BROWN"],
        ["s", "Strangler", "DGRAY"],
        ["s", "Swan", "WHITE"],
        ["s", "Swan man", "WHITE"],
        ["T", "Tapir", "WHITE"],
        ["T", "Tapir man", "WHITE"],
        ["t", "Thrips man", "BROWN"],
        ["t", "Tick man", "DGRAY"],
        ["T", "Tiger", "YELLOW"],
        ["T", "Tiger man", "YELLOW"],
        ["t", "Toad man", "GREEN"],
        ["t", "Turkey", "LRED"],
        ["C", "Two-humped camel", "BROWN"],
        ["C", "Two-humped camel man", "BROWN"],
        ["U", "Unicorn", "WHITE"],
        ["v", "Vulture", "RED"],
        ["v", "Vulture man", "RED"],
        ["W", "Warthog", "BROWN"],
        ["W", "Warthog man", "BROWN"],
        ["W", "Water buffalo", "DGRAY"],
        ["w", "Weasel", "BROWN"],
        ["w", "Weasel man", "BROWN"],
        ["s", "White stork", "WHITE"],
        ["s", "White stork man", "WHITE"],
        ["g", "White-browed gibbon", "WHITE"],
        ["g", "White-handed gibbon", "BROWN"],
        ["B", "Wild boar", "BROWN"],
        ["B", "Wild boar man", "BROWN"],
        ["w", "Wolf", "LGRAY"],
        ["w", "Wolf man", "LGRAY"],
        ["w", "Wolverine", "BROWN"],
        ["w", "Wolverine man", "BROWN"],
        ["w", "Wombat", "BROWN"],
        ["w", "Wombat man", "BROWN"],
        ["w", "Worm man", "LGRAY"],
        ["w", "Wren man", "BROWN"],
        ["Y", "Yak", "BROWN"],
        ["Y", "Yeti", "WHITE"]
    ],
    Subterranean: [
        ["B", "Blind cave bear", "WHITE"],
        ["O", "Blind cave ogre", "WHITE"],
        ["M", "Blood man", "RED"],
        ["b", "Bugbat", "MAGENTA"],
        ["o", "Cave blob", "YELLOW"],
        ["C", "Cave crocodile", "LGRAY"],
        ["D", "Cave dragon", "WHITE"],
        ["f", "Cave floater", "YELLOW"],
        ["e", "Creeping eye", "WHITE"],
        ["c", "Crundle", "RED"],
        ["D", "Draltha", "YELLOW"],
        ["d", "Drunian", "LGRAY"],
        ["E", "Elk bird", "BROWN"],
        ["i", "Fire imp", "YELLOW"],
        ["M", "Fire man", "LRED"],
        ["o", "Flesh ball", "BROWN"],
        ["%", "Floating guts", "LGRAY"],
        ["M", "Gabbro man", "DGRAY"],
        ["B", "Giant bat", "DGRAY"],
        ["S", "Giant cave spider", "LGRAY"],
        ["C", "Giant cave swallow", "DGRAY"],
        ["T", "Giant cave toad", "LGRAY"],
        ["W", "Giant earthworm", "LGRAY"],
        ["m", "Giant mole", "BROWN"],
        ["O", "Giant olm", "WHITE"],
        ["R", "Giant rat", "DGRAY"],
        ["g", "Gorlak", "YELLOW"],
        ["G", "Green devourer", "LGREEN"],
        ["g", "Gremlin", "LGREEN"],
        ["s", "Helmet snake", "WHITE"],
        ["h", "Hungry head", "DGRAY"],
        ["M", "Iron man", "DGRAY"],
        ["J", "Jabberer", "LMAGENTA"],
        ["r", "Large rat", "BROWN"],
        ["C", "Magma crab", "DGRAY"],
        ["M", "Magma man", "LRED"],
        ["m", "Manera", "BROWN"],
        ["M", "Molemarian", "LRED"],
        ["M", "Mud man", "BROWN"],
        ["n", "Naked mole dog", "LRED"],
        ["m", "Plump helmet man", "MAGENTA"],
        ["p", "Pond grabber", "LBLUE"],
        ["R", "Reacher", "LGRAY"],
        ["R", "Rutherer", "LGRAY"],
        ["t", "Troglodyte", "BROWN"],
        ["T", "Troll", "DGRAY"],
        ["C", "Voracious cave crawler", "BLUE"]
    ],
    Aquatic: [
        ["a", "Albatross man", "WHITE"],
        ["A", "Alligator", "GREEN"],
        ["A", "Alligator man", "GREEN"],
        ["T", "Alligator snapping turtle", "GREEN"],
        ["s", "Angelshark", "BROWN"],
        ["a", "Axolotl man", "MAGENTA"],
        ["S", "Basking shark", "LGRAY"],
        ["B", "Beak dog", "RED"],
        ["b", "Beaver", "BROWN"],
        ["b", "Beaver man", "BROWN"],
        ["s", "Blacktip reef shark", "DGRAY"],
        ["S", "Blue shark", "LBLUE"],
        ["a", "Bluefin tuna", "LBLUE"],
        ["a", "Bluefish", "LCYAN"],
        ["S", "Bull shark", "WHITE"],
        ["b", "Buzzard", "DGRAY"],
        ["b", "Buzzard man", "DGRAY"],
        ["a", "Carp", "CYAN"],
        ["a", "Cod", "LGRAY"],
        ["C", "Coelacanth", "LBLUE"],
        ["&#xF2;", "Common skate", "BROWN"],
        ["t", "Common snapping turtle", "GREEN"],
        ["~", "Conger eel", "LGRAY"],
        ["c", "Crab", "LRED"],
        ["c", "Crab man", "LRED"],
        ["c", "Cuttlefish man", "BROWN"],
        ["d", "Damselfly man", "LCYAN"],
        ["d", "Dragonfly man", "LCYAN"],
        ["d", "Duck", "GREEN"],
        ["S", "Elephant seal", "BROWN"],
        ["S", "Elephant seal man", "BROWN"],
        ["p", "Emperor penguin", "WHITE"],
        ["f", "Fly man", "DGRAY"],
        ["s", "Frill shark", "CYAN"],
        ["A", "Giant albatross", "WHITE"],
        ["A", "Giant alligator", "GREEN"],
        ["A", "Giant axolotl", "MAGENTA"],
        ["B", "Giant beaver", "BROWN"],
        ["B", "Giant buzzard", "DGRAY"],
        ["C", "Giant crab", "LRED"],
        ["C", "Giant cuttlefish", "BROWN"],
        ["D", "Giant damselfly", "LCYAN"],
        ["D", "Giant dragonfly", "LCYAN"],
        ["S", "Giant elephant seal", "BROWN"],
        ["F", "Giant fly", "DGRAY"],
        ["F", "Giant green tree frog", "LGREEN"],
        ["G", "Giant grouper", "BLUE"],
        ["H", "Giant harp seal", "LGRAY"],
        ["H", "Giant hippo", "LGRAY"],
        ["C", "Giant horseshoe crab", "BROWN"],
        ["K", "Giant kestrel", "RED"],
        ["L", "Giant leech", "DGRAY"],
        ["L", "Giant leopard seal", "DGRAY"],
        ["L", "Giant loon", "DGRAY"],
        ["M", "Giant mink", "BROWN"],
        ["S", "Giant moon snail", "LRED"],
        ["M", "Giant mosquito", "DGRAY"],
        ["N", "Giant narwhal", "LGRAY"],
        ["N", "Giant nautilus", "LRED"],
        ["O", "Giant octopus", "LGRAY"],
        ["O", "Giant orca", "DGRAY"],
        ["O", "Giant osprey", "WHITE"],
        ["O", "Giant otter", "BROWN"],
        ["P", "Giant penguin", "DGRAY"],
        ["P", "Giant platypus", "BROWN"],
        ["T", "Giant pond turtle", "GREEN"],
        ["P", "Giant puffin", "DGRAY"],
        ["R", "Giant red-winged blackbird", "DGRAY"],
        ["C", "Giant saltwater crocodile", "GREEN"],
        ["T", "Giant snapping turtle", "GREEN"],
        ["W", "Giant sperm whale", "LGRAY"],
        ["S", "Giant sponge", "LRED"],
        ["S", "Giant swan", "WHITE"],
        ["T", "Giant toad", "GREEN"],
        ["W", "Giant walrus", "BROWN"],
        ["S", "Gigantic squid", "WHITE"],
        ["g", "Goose", "WHITE"],
        ["b", "Great barracuda", "GREEN"],
        ["S", "Great white shark", "WHITE"],
        ["f", "Green tree frog man", "LGREEN"],
        ["g", "Grimeling", "GREEN"],
        ["a", "Halibut", "BROWN"],
        ["S", "Hammerhead shark", "BROWN"],
        ["H", "Harp seal", "LGRAY"],
        ["h", "Harp seal man", "LGRAY"],
        ["h", "Harpy", "BROWN"],
        ["H", "Hippo", "LGRAY"],
        ["H", "Hippo man", "LGRAY"],
        ["c", "Horseshoe crab", "BROWN"],
        ["c", "Horseshoe crab man", "BROWN"],
        ["k", "Kestrel", "RED"],
        ["k", "Kestrel man", "RED"],
        ["l", "Leech man", "DGRAY"],
        ["L", "Leopard seal", "DGRAY"],
        ["L", "Leopard seal man", "DGRAY"],
        ["p", "Little penguin", "LBLUE"],
        ["S", "Longfin mako shark", "LCYAN"],
        ["g", "Longnose gar", "BROWN"],
        ["l", "Loon", "DGRAY"],
        ["l", "Loon man", "DGRAY"],
        ["&#x00ca;", "Manta ray", "LGRAY"],
        ["a", "Marlin", "LBLUE"],
        ["M", "Merperson", "LCYAN"],
        ["a", "Milkfish", "LCYAN"],
        ["m", "Mink", "BROWN"],
        ["m", "Mink man", "BROWN"],
        ["s", "Moon snail man", "LRED"],
        ["m", "Mosquito man", "DGRAY"],
        ["N", "Narwhal", "LGRAY"],
        ["N", "Narwhal man", "LGRAY"],
        ["n", "Nautilus man", "LRED"],
        ["S", "Nurse shark", "BROWN"],
        ["a", "Ocean sunfish", "CYAN"],
        ["o", "Octopus", "LGRAY"],
        ["o", "Octopus man", "LGRAY"],
        ["a", "Opah", "LRED"],
        ["O", "Orca", "DGRAY"],
        ["O", "Orca man", "DGRAY"],
        ["o", "Osprey", "WHITE"],
        ["o", "Osprey man", "WHITE"],
        ["o", "Otter man", "BROWN"],
        ["p", "Penguin", "DGRAY"],
        ["p", "Penguin man", "WHITE"],
        ["a", "Pike", "GREEN"],
        ["p", "Platypus", "BROWN"],
        ["p", "Platypus man", "BROWN"],
        ["t", "Pond turtle man", "GREEN"],
        ["p", "Puffin", "DGRAY"],
        ["p", "Puffin man", "DGRAY"],
        ["r", "Red-winged blackbird man", "DGRAY"],
        ["o", "River otter", "BROWN"],
        ["C", "Saltwater crocodile", "GREEN"],
        ["C", "Saltwater crocodile man", "GREEN"],
        ["~", "Sea lamprey", "DGRAY"],
        ["M", "Sea monster", "DGRAY"],
        ["o", "Sea otter", "BROWN"],
        ["S", "Sea serpent", "LCYAN"],
        ["S", "Shortfin mako shark", "LCYAN"],
        ["t", "Snapping turtle man", "GREEN"],
        ["W", "Sperm whale", "LGRAY"],
        ["W", "Sperm whale man", "LGRAY"],
        ["s", "Spiny dogfish", "BROWN"],
        ["s", "Sponge", "LRED"],
        ["s", "Sponge man", "LRED"],
        ["S", "Spotted wobbegong", "BROWN"],
        ["s", "Squid man", "WHITE"],
        ["&#xf2;", "Stingray", "LGRAY"],
        ["a", "Sturgeon", "BROWN"],
        ["s", "Swan", "WHITE"],
        ["s", "Swan man", "WHITE"],
        ["a", "Swordfish", "LCYAN"],
        ["S", "Tiger shark", "LGRAY"],
        ["a", "Tigerfish", "LCYAN"],
        ["t", "Toad man", "GREEN"],
        ["W", "Walrus", "BROWN"],
        ["W", "Walrus man", "BROWN"],
        ["W", "Whale shark", "BROWN"],
        ["s", "Whitetip reef shark", "WHITE"]
    ],
    Other: [
        ["Any", "Forgotten beast", "WHITE"],
        ["Any", "Titan", "WHITE"],
        ["&#xd1;", "Night troll", "LGREEN"],
        ["&#xf1;", "Bogeyman", "DGRAY"],
        ["&#xd1;", "Werebeast", "BROWN"]
    ]
}
